* DataSourceErrorLoggingAspect - аспект перехватывающий выброс исключения.
* LogDataError - аннотация использующаяся для перехвата.
* Организовано тестовое добавление данных в H2 (чтобы не настраивать контейнеризацию с другими бд).
* тк Spring AOP проксирует только вызовы «извне» через прокси-бина, я создал специально ErrorService который сохраняет Null в бд и выбрасывает исключение.

**Работает свагер с помощью которого можно проверить добавление логов в БД и соотвественно что все объекты добавлены в БД** [Тык!](http://localhost:8080/swagger-ui.html)

Отработка аспекта видна в логах

Hibernate: 

    insert 
    into
        data_source_error_log
        (message, signature_method, stack_trace, timestamp, id)
    values
        (?, ?, ?, ?, default)
        
Генератор: Искусственная ошибка обработана

Мы видим что при исключении Hibernate отправляет данные в таблицу с логами ошибок в бд.
